name: Upload coverage reports to Codecov

on:
  push:
    branches:
      - main  

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: 2457104-Simphiwe/my-car-static-web-app

